const { esc, num } = require("./escapeHtml");
const { getBlueprint } = require("../config/examBlueprint");

/**
 * Renders the full analytical dashboard: exam result + report object in, a
 * single self-contained HTML document out.
 *
 * Self-contained on purpose — no CDN fonts, no external CSS, no JS
 * dependencies. That means it can be dropped into an iframe in the Speak2Go
 * UI, emailed as a file, or handed straight to Puppeteer for the PDF, with
 * identical output in all three.
 *
 * @param {object} examResult - output of evaluateFullExam()
 * @param {object} report     - output of buildReportObject()
 * @param {object} meta       - { studentName, examLevel, dateExecuted, examId }
 */
function renderDashboardHtml(examResult, report, meta = {}) {
  const results = examResult.question_results || [];
  const blueprint = safeBlueprint(examResult.level, examResult.exam_layout);

  const analytics = computeAnalytics(examResult, results, blueprint);

  return `<!DOCTYPE html>
<html lang="en"><head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${esc(meta.studentName || "Student")} — Oral Exam Evaluation</title>
<style>${STYLES}</style>
</head>
<body>
<div class="page">

  ${renderHeader(examResult, meta)}
  ${renderStatStrip(examResult, analytics)}
  ${renderPipeline(analytics)}

  <div class="grid-2">
    ${renderPartBreakdown(analytics)}
    ${renderCriterionProfile(analytics)}
  </div>

  ${renderQuestions(results, analytics)}
  ${renderDeductions(report)}
  ${renderRecommendations(report)}

  <footer class="footer">
    Generated by the Speak2Go automated COBE evaluation module ·
    ${esc(new Date().toISOString().slice(0, 16).replace("T", " "))} UTC ·
    Scores are machine-generated and intended to support, not replace, examiner judgement.
  </footer>
</div>
</body></html>`;
}

/* ------------------------------------------------------------------ *
 * Derived analytics
 * ------------------------------------------------------------------ */

/**
 * The slot list to lay the report out against.
 *
 * Prefer the layout the exam was actually built from (examResult.exam_layout,
 * as produced by examBlueprint.inspectLesson). Part B is one question in the
 * 2019-2022 lessons and a two-question set in the 2023 ones, so falling back
 * to the default blueprint on a 2023 exam would render an empty "Part B -
 * Project Presentation" slot and hide the two questions the student answered.
 */
function safeBlueprint(level, examLayout) {
  if (Array.isArray(examLayout) && examLayout.length) return examLayout;
  try {
    return getBlueprint(level);
  } catch {
    return [];
  }
}

function computeAnalytics(examResult, results, blueprint) {
  const byId = Object.fromEntries(results.map((r) => [String(r.question_id), r]));

  // Points per exam part, against what each part is worth
  const partTotals = {};
  for (const bp of blueprint) {
    if (!partTotals[bp.part]) partTotals[bp.part] = { part: bp.part, possible: 0, earned: 0, questions: [] };
    partTotals[bp.part].possible += bp.points;
    const r = byId[bp.question_id];
    if (r) {
      partTotals[bp.part].earned += (r.final_question_score / 100) * (r.weight || bp.points);
    }
    partTotals[bp.part].questions.push({ ...bp, result: r || null });
  }

  // Average score per rubric criterion, across every scored question
  const criterionAcc = {};
  for (const r of results) {
    for (const c of r.criterion_breakdown || []) {
      if (!criterionAcc[c.criterion_name]) criterionAcc[c.criterion_name] = { total: 0, n: 0, weight: c.weight };
      criterionAcc[c.criterion_name].total += c.criterion_score;
      criterionAcc[c.criterion_name].n += 1;
    }
  }
  const criterionAverages = Object.entries(criterionAcc)
    .map(([name, v]) => ({ name, average: v.total / v.n, weight: v.weight }))
    .sort((a, b) => a.average - b.average);

  const scored = results.filter((r) => (r.criterion_breakdown || []).length > 0);
  const deductionCount = results.reduce((s, r) => s + (r.deductions || []).length, 0);

  const fluencyLevels = results
    .map((r) => r.audio_metrics && r.audio_metrics.fluencyLevel)
    .filter((n) => typeof n === "number");
  const avgFluency = fluencyLevels.length
    ? fluencyLevels.reduce((a, b) => a + b, 0) / fluencyLevels.length
    : null;

  const totalSpeech = results.reduce(
    (s, r) => s + ((r.audio_metrics && r.audio_metrics.totalDurationSeconds) || 0),
    0
  );

  return {
    parts: Object.values(partTotals),
    criterionAverages,
    scoredCount: scored.length,
    attemptedCount: results.length,
    blueprintCount: blueprint.length || results.length,
    unattempted: examResult.unattempted_questions || [],
    deductionCount,
    avgFluency,
    totalSpeech,
    weakestCriterion: criterionAverages[0] || null,
    strongestCriterion: criterionAverages[criterionAverages.length - 1] || null,
  };
}

/* ------------------------------------------------------------------ *
 * Sections
 * ------------------------------------------------------------------ */

const band = (s) => (s >= 85 ? "high" : s >= 60 ? "mid" : "low");

function renderHeader(examResult, meta) {
  const score = Number(examResult.overall_score);
  const pct = Number.isFinite(score) ? Math.max(0, Math.min(100, score)) : 0;
  const R = 52;
  const C = 2 * Math.PI * R;

  return `
  <header class="header">
    <div class="header-id">
      <div class="eyebrow">Automated Oral Exam Evaluation</div>
      <h1>${esc(meta.studentName || "Student")}</h1>
      <div class="header-meta">
        ${meta.examLevel ? `<span class="tag">${esc(meta.examLevel)}</span>` : ""}
        ${examResult.level ? `<span class="tag tag-quiet">${esc(examResult.level)}</span>` : ""}
        ${meta.dateExecuted ? `<span class="dot">·</span><span>${esc(meta.dateExecuted)}</span>` : ""}
        ${meta.examId ? `<span class="dot">·</span><span class="mono">${esc(meta.examId)}</span>` : ""}
      </div>
    </div>

    <div class="score-dial band-${band(pct)}">
      <svg viewBox="0 0 128 128" width="128" height="128" role="img" aria-label="Overall score ${num(score)} out of 100">
        <circle class="dial-track" cx="64" cy="64" r="${R}" />
        <circle class="dial-value" cx="64" cy="64" r="${R}"
                stroke-dasharray="${C.toFixed(1)}"
                stroke-dashoffset="${(C * (1 - pct / 100)).toFixed(1)}"
                transform="rotate(-90 64 64)" />
      </svg>
      <div class="score-inner">
        <div class="score-num">${num(score)}</div>
        <div class="score-den">out of 100</div>
      </div>
    </div>
  </header>`;
}

function renderStatStrip(examResult, a) {
  const fluencyText = a.avgFluency === null ? "—" : `${a.avgFluency.toFixed(1)} / 4`;
  const mins = Math.floor(a.totalSpeech / 60);
  const secs = Math.round(a.totalSpeech % 60);

  const stats = [
    {
      label: "Points earned",
      value: `${num(examResult.points_earned, 1)}`,
      sub: `of ${esc(examResult.points_possible ?? 100)} available`,
    },
    {
      label: "Questions scored",
      value: `${a.scoredCount} / ${a.blueprintCount}`,
      sub: a.unattempted.length
        ? `${a.unattempted.length} never attempted`
        : a.scoredCount < a.attemptedCount
          ? `${a.attemptedCount - a.scoredCount} zeroed by penalty`
          : "all questions scored",
      tone: a.scoredCount < a.blueprintCount ? "warn" : "ok",
    },
    {
      label: "Deductions applied",
      value: String(a.deductionCount),
      sub: a.deductionCount ? "see breakdown below" : "none",
      tone: a.deductionCount ? "warn" : "ok",
    },
    {
      label: "Average fluency",
      value: fluencyText,
      sub: `${mins}m ${secs}s of speech`,
    },
  ];

  return `
  <section class="stat-strip">
    ${stats
      .map(
        (s) => `
      <div class="stat ${s.tone ? "stat-" + s.tone : ""}">
        <div class="stat-label">${esc(s.label)}</div>
        <div class="stat-value">${esc(s.value)}</div>
        <div class="stat-sub">${esc(s.sub)}</div>
      </div>`
      )
      .join("")}
  </section>`;
}

/**
 * The processing pipeline, rendered as a flow so a teacher (or the client)
 * can see exactly which stages produced the number at the top — and, more
 * importantly, which stages are deterministic rules versus model judgement.
 */
function renderPipeline(a) {
  const stages = [
    { n: "1", name: "Audio intake", detail: "Student recording", kind: "io" },
    { n: "2", name: "Speech-to-text", detail: "Deepgram, word timings", kind: "io" },
    { n: "3", name: "Speech metrics", detail: "Pauses · WPM · fillers", kind: "det" },
    { n: "4", name: "Rubric scoring", detail: "9 sub-criteria × 4 levels", kind: "llm" },
    { n: "5", name: "Aggregation", detail: "Criterion → question", kind: "det" },
    { n: "6", name: "Penalties", detail: "Coverage · time · flags", kind: "det" },
    { n: "7", name: "Report", detail: "Scored out of 100", kind: "out" },
  ];

  return `
  <section class="card pipeline-card">
    <div class="card-head">
      <h2>Evaluation pipeline</h2>
      <div class="legend">
        <span class="lg lg-det"></span> Deterministic rule
        <span class="lg lg-llm"></span> Model judgement
        <span class="lg lg-io"></span> External service
      </div>
    </div>
    <div class="pipeline">
      ${stages
        .map(
          (s, i) => `
        <div class="stage stage-${s.kind}">
          <div class="stage-n">${esc(s.n)}</div>
          <div class="stage-name">${esc(s.name)}</div>
          <div class="stage-detail">${esc(s.detail)}</div>
        </div>
        ${i < stages.length - 1 ? `<div class="stage-arrow" aria-hidden="true"></div>` : ""}`
        )
        .join("")}
    </div>
    <p class="pipeline-note">
      Only stage 4 involves model judgement, and it is constrained to picking one of four
      fixed rubric levels per sub-criterion. Every score-affecting calculation after that
      point — weighting, coverage deductions, time bands, and the 0-for-section rules — is
      deterministic and reproducible.
    </p>
  </section>`;
}

function renderPartBreakdown(a) {
  const partNames = { A: "Part A · Personal Response", B: "Part B · Project Presentation", C: "Part C · Audio-Visual" };

  if (!a.parts.length) return `<section class="card"><div class="card-head"><h2>Part breakdown</h2></div><p class="empty">No part data.</p></section>`;

  return `
  <section class="card">
    <div class="card-head"><h2>Points by exam part</h2></div>
    <div class="parts">
      ${a.parts
        .map((p) => {
          const pct = p.possible ? (p.earned / p.possible) * 100 : 0;
          return `
        <div class="part-row">
          <div class="part-top">
            <span class="part-name">${esc(partNames[p.part] || "Part " + p.part)}</span>
            <span class="part-points"><strong>${num(p.earned)}</strong> / ${esc(p.possible)}</span>
          </div>
          <div class="bar">
            <div class="bar-fill band-${band(pct)}" style="width:${pct.toFixed(1)}%"></div>
          </div>
        </div>`;
        })
        .join("")}
    </div>
  </section>`;
}

function renderCriterionProfile(a) {
  if (!a.criterionAverages.length) {
    return `<section class="card"><div class="card-head"><h2>Criterion profile</h2></div>
      <p class="empty">No questions were scored against the rubric — every answer was zeroed by a penalty rule before evaluation.</p></section>`;
  }

  return `
  <section class="card">
    <div class="card-head">
      <h2>Criterion profile</h2>
      <span class="card-sub">averaged across scored questions</span>
    </div>
    <div class="criteria">
      ${a.criterionAverages
        .map(
          (c) => `
        <div class="crit-row">
          <div class="crit-name">${esc(c.name)} <span class="crit-weight">${num(c.weight * 100, 0)}%</span></div>
          <div class="bar bar-sm"><div class="bar-fill band-${band(c.average)}" style="width:${Math.max(0, Math.min(100, c.average)).toFixed(1)}%"></div></div>
          <div class="crit-val">${num(c.average)}</div>
        </div>`
        )
        .join("")}
    </div>
    ${
      a.weakestCriterion && a.strongestCriterion && a.criterionAverages.length > 1
        ? `<p class="insight">Weakest area is <strong>${esc(a.weakestCriterion.name)}</strong>
             (${num(a.weakestCriterion.average)}), strongest is <strong>${esc(a.strongestCriterion.name)}</strong>
             (${num(a.strongestCriterion.average)}).</p>`
        : ""
    }
  </section>`;
}

function renderQuestions(results, a) {
  const unattemptedCards = a.unattempted
    .map(
      (u) => `
    <article class="card q-card q-missing">
      <div class="q-head">
        <span class="q-id">Q${esc(u.question_id)}</span>
        <span class="q-desc">${esc(u.description)}</span>
        <span class="q-score band-low">0.0</span>
      </div>
      <div class="q-flag">Not attempted — forfeits ${esc(u.points_forfeited)} points.</div>
    </article>`
    )
    .join("");

  return `
  <section class="section">
    <h2 class="section-title">Question-by-question</h2>
    ${results.map(renderQuestionCard).join("")}
    ${unattemptedCards}
  </section>`;
}

function renderQuestionCard(r) {
  const m = r.audio_metrics || {};
  const zeroed = !(r.criterion_breakdown || []).length;

  const metricChips = [
    m.totalDurationSeconds != null ? `${num(m.totalDurationSeconds, 0)}s` : null,
    m.wpm ? `${esc(m.wpm)} wpm` : null,
    m.pauseCount != null ? `${esc(m.pauseCount)} long pause${m.pauseCount === 1 ? "" : "s"}` : null,
    m.fillerWordCount != null ? `${esc(m.fillerWordCount)} fillers` : null,
    m.fluencyLevel ? `fluency ${esc(m.fluencyLevel)}/4` : null,
  ].filter(Boolean);

  return `
  <article class="card q-card">
    <div class="q-head">
      <span class="q-id">Q${esc(r.question_id)}</span>
      <span class="q-desc">${esc(r.description)}</span>
      <span class="q-weight">${esc(r.weight)} pts</span>
      <span class="q-score band-${band(r.final_question_score)}">${num(r.final_question_score)}</span>
    </div>

    ${metricChips.length ? `<div class="chips">${metricChips.map((c) => `<span class="chip">${c}</span>`).join("")}</div>` : ""}

    ${
      zeroed
        ? `<div class="q-flag">Zeroed by a penalty rule before rubric evaluation — no criterion scores were produced.</div>`
        : `<div class="criteria criteria-inline">
            ${(r.criterion_breakdown || [])
              .map(
                (c) => `
              <div class="crit-row">
                <div class="crit-name">${esc(c.criterion_name)} <span class="crit-weight">${num(c.weight * 100, 0)}%</span></div>
                <div class="bar bar-sm"><div class="bar-fill band-${band(c.criterion_score)}" style="width:${Math.max(0, Math.min(100, c.criterion_score)).toFixed(1)}%"></div></div>
                <div class="crit-val">${num(c.criterion_score)}</div>
              </div>
              ${
                (c.sub_criteria || []).length
                  ? `<div class="subs">${c.sub_criteria
                      .map(
                        (s) => `<span class="sub band-${band(s.score)}">${esc(s.name)} <b>${esc(s.score)}</b></span>`
                      )
                      .join("")}</div>`
                  : ""
              }`
              )
              .join("")}
          </div>`
    }

    ${
      (r.deductions || []).length
        ? `<div class="q-deductions">${r.deductions
            .map((d) => `<span class="ded">−${esc(d.deduction)}% · ${esc(d.reason)}</span>`)
            .join("")}</div>`
        : ""
    }
    ${r.coverage_note ? `<div class="q-note">${esc(r.coverage_note)}</div>` : ""}
    ${
      r.transcript
        ? `<details class="transcript">
             <summary>Transcript (${esc(String(r.transcript).trim().split(/\s+/).length)} words)</summary>
             <p>${esc(r.transcript)}</p>
           </details>`
        : ""
    }
  </article>`;
}

function renderDeductions(report) {
  const rows = report.deductionsTable || [];
  return `
  <section class="card">
    <div class="card-head"><h2>Deductions</h2></div>
    ${
      rows.length
        ? `<table class="table">
            <thead><tr><th>Question</th><th>Reason</th><th class="right">Deduction</th></tr></thead>
            <tbody>
              ${rows
                .map(
                  (d) => `<tr>
                    <td class="mono">Q${esc(d.questionId)}</td>
                    <td>${esc(d.reason)}</td>
                    <td class="right neg">−${esc(d.deduction)}%</td>
                  </tr>`
                )
                .join("")}
            </tbody>
          </table>
          <p class="table-note">Deductions within a question are not additive — the largest applicable
          deduction is applied, per the Ministry rubric's "0% for the entire section" wording.</p>`
        : `<p class="empty">No deductions were applied.</p>`
    }
  </section>`;
}

function renderRecommendations(report) {
  return `
  <section class="card reco-card">
    <div class="card-head"><h2>Teacher recommendations</h2></div>
    <div class="reco">${esc(report.teacherRecommendations) || "—"}</div>
  </section>`;
}

/* ------------------------------------------------------------------ *
 * Styles
 * ------------------------------------------------------------------ */

/* Palette is the Speak2Go logo's, kept in step with public/styles.css so the
   downloadable report, the inline dashboard and the live UI are one brand.

   Same three-depth rule as the live UI: --brand is the logo blue and is only
   ever a FILL, because white text on it is ~2.4:1 and fails AA. --brand-700 is
   the only blue that carries text on white. The score bands stay green/amber/
   red rather than shifting to brand tints — this document is the artefact a
   grade gets disputed from, so pass/fail has to read at a glance and must not
   be confusable with a decorative brand accent. */
const STYLES = `
:root{
  --brand:#17adf2; --brand-600:#0b8fd6; --brand-700:#0a6e9e;
  --brand-tint:#e9f6fe; --brand-tint-2:#cbe8fa;
  --ink:#1f2730; --ink-2:#46545f; --muted:#667582; --line:#dde8f1;
  --bg:#f2f7fb; --surface:#ffffff; --surface-2:#f6fafd;
  --high:#12925f; --mid:#b0730a; --low:#d0402f;
  --accent:#0a6e9e;
  --high-bg:#e6f6ef; --mid-bg:#fdf4e3; --low-bg:#fdedeb;
}
*{box-sizing:border-box}
body{
  margin:0; background:var(--bg); color:var(--ink);
  font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Inter,Roboto,Helvetica,Arial,sans-serif;
  font-size:14px; line-height:1.5; -webkit-font-smoothing:antialiased;
}
.page{max-width:1080px; margin:0 auto; padding:32px 28px 56px}
h1,h2{margin:0; letter-spacing:-.01em}
.mono{font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace; font-size:.92em}
.right{text-align:right}

/* header */
/* The brand shows up as a strip along the top of the header card rather than
   a filled banner: this document is printed and PDF'd, and a full-bleed blue
   block costs a lot of toner for no added meaning. */
.header{
  position:relative; overflow:hidden;
  display:flex; justify-content:space-between; align-items:center; gap:24px;
  background:var(--surface); border:1px solid var(--line); border-radius:14px;
  padding:26px 28px; margin-bottom:16px;
}
.header::before{
  content:""; position:absolute; top:0; left:0; right:0; height:4px;
  background:linear-gradient(90deg,var(--brand) 0%,var(--brand-600) 60%,#0778b4 100%);
}
.eyebrow{font-size:11px; font-weight:700; letter-spacing:.09em; text-transform:uppercase; color:var(--accent); margin-bottom:6px}
.header h1{font-size:26px; font-weight:700}
.header-meta{display:flex; align-items:center; gap:8px; flex-wrap:wrap; margin-top:10px; color:var(--muted); font-size:12.5px}
.tag{background:var(--brand-tint); color:var(--ink-2); border-radius:5px; padding:3px 9px; font-weight:600; font-size:11.5px}
.tag-quiet{background:transparent; border:1px solid var(--line); color:var(--muted); font-weight:500}
.dot{color:#b9cdda}

.score-dial{position:relative; width:128px; height:128px; flex-shrink:0}
.dial-track{fill:none; stroke:var(--line); stroke-width:11}
.dial-value{fill:none; stroke-width:11; stroke-linecap:round; transition:stroke-dashoffset .6s ease}
.band-high .dial-value{stroke:var(--high)} .band-mid .dial-value{stroke:var(--mid)} .band-low .dial-value{stroke:var(--low)}
.score-inner{position:absolute; inset:0; display:flex; flex-direction:column; align-items:center; justify-content:center}
.score-num{font-size:32px; font-weight:700; letter-spacing:-.03em; font-variant-numeric:tabular-nums; line-height:1}
.score-den{font-size:10.5px; color:var(--muted); margin-top:3px}

/* stats */
.stat-strip{display:grid; grid-template-columns:repeat(4,1fr); gap:12px; margin-bottom:16px}
.stat{background:var(--surface); border:1px solid var(--line); border-radius:11px; padding:15px 17px}
.stat-label{font-size:11px; font-weight:600; letter-spacing:.05em; text-transform:uppercase; color:var(--muted)}
.stat-value{font-size:23px; font-weight:700; letter-spacing:-.02em; margin:5px 0 2px; font-variant-numeric:tabular-nums}
.stat-sub{font-size:12px; color:var(--muted)}
.stat-warn{border-color:#f0dcc0; background:#fffdf8}
.stat-warn .stat-value{color:var(--mid)}

/* cards */
.card{background:var(--surface); border:1px solid var(--line); border-radius:12px; padding:20px 22px; margin-bottom:16px}
.card-head{display:flex; align-items:baseline; justify-content:space-between; gap:12px; margin-bottom:16px}
.card-head h2{font-size:15px; font-weight:700}
.card-sub{font-size:12px; color:var(--muted)}
.section{margin-bottom:16px}
.section-title{font-size:15px; font-weight:700; margin:26px 0 12px}
.empty{color:var(--muted); font-size:13px; margin:0}
.grid-2{display:grid; grid-template-columns:1fr 1fr; gap:16px}

/* pipeline */
.legend{font-size:11.5px; color:var(--muted); display:flex; align-items:center; gap:6px}
.lg{width:9px; height:9px; border-radius:2px; display:inline-block; margin-left:8px}
.lg-det{background:var(--accent)} .lg-llm{background:#8557b8} .lg-io{background:#7b8fa0}
.pipeline{display:flex; align-items:stretch; gap:0; overflow-x:auto; padding-bottom:4px}
.stage{flex:1 1 0; min-width:112px; border:1px solid var(--line); border-top:3px solid #7b8fa0; border-radius:9px; padding:12px 11px; background:var(--surface-2); display:flex; flex-direction:column}
.stage-det{border-top-color:var(--accent)} .stage-llm{border-top-color:#8557b8; background:#faf7fd} .stage-out{border-top-color:var(--high); background:#f1faf5}
.stage-n{font-size:10px; font-weight:700; color:var(--muted); font-variant-numeric:tabular-nums}
.stage-name{font-size:12px; font-weight:700; margin:3px 0 5px; letter-spacing:-.015em; line-height:1.25}
.stage-detail{font-size:10.5px; color:var(--muted); line-height:1.4; margin-top:auto}
.stage-arrow{flex:0 0 13px; position:relative}
.stage-arrow::before{content:""; position:absolute; top:50%; left:2px; right:2px; height:1.5px; background:var(--line)}
.stage-arrow::after{content:""; position:absolute; top:50%; right:2px; width:5px; height:5px; border-top:1.5px solid #c3d5e3; border-right:1.5px solid #c3d5e3; transform:translateY(-50%) rotate(45deg)}
.pipeline-note{font-size:12px; color:var(--muted); margin:14px 0 0; line-height:1.55; max-width:78ch}

/* bars */
.bar{background:#e4eef6; border-radius:99px; height:8px; overflow:hidden}
.bar-sm{height:6px}
.bar-fill{height:100%; border-radius:99px}
.bar-fill.band-high{background:var(--high)} .bar-fill.band-mid{background:var(--mid)} .bar-fill.band-low{background:var(--low)}

.parts .part-row{margin-bottom:15px}
.parts .part-row:last-child{margin-bottom:0}
.part-top{display:flex; justify-content:space-between; align-items:baseline; margin-bottom:6px}
.part-name{font-size:12.5px; font-weight:600}
.part-points{font-size:12.5px; color:var(--muted); font-variant-numeric:tabular-nums}
.part-points strong{color:var(--ink); font-size:14px}

.crit-row{display:grid; grid-template-columns:minmax(140px,215px) 1fr 42px; align-items:center; gap:14px; margin-bottom:9px}
.crit-name{font-size:12.5px; font-weight:500; white-space:nowrap}
.crit-weight{color:var(--muted); font-size:11px; margin-left:4px}
.crit-val{font-size:12.5px; font-weight:700; text-align:right; font-variant-numeric:tabular-nums}
.insight{font-size:12.5px; color:var(--ink-2); margin:14px 0 0; padding-top:13px; border-top:1px solid var(--line)}

/* question cards */
.q-card{padding:18px 20px}
.q-head{display:flex; align-items:center; gap:11px; padding-bottom:12px; border-bottom:1px solid var(--line); margin-bottom:13px}
.q-id{font-weight:700; font-size:13px; background:var(--brand-tint); color:var(--brand-700); border-radius:5px; padding:3px 8px; font-variant-numeric:tabular-nums}
.q-desc{flex:1; font-size:12.5px; color:var(--ink-2)}
.q-weight{font-size:11.5px; color:var(--muted); white-space:nowrap}
.q-score{font-size:19px; font-weight:700; font-variant-numeric:tabular-nums; letter-spacing:-.02em}
.q-score.band-high{color:var(--high)} .q-score.band-mid{color:var(--mid)} .q-score.band-low{color:var(--low)}
.q-missing{background:var(--surface-2); border-style:dashed}

.chips{display:flex; flex-wrap:wrap; gap:6px; margin-bottom:13px}
.chip{font-size:11px; background:#eef4f9; color:var(--ink-2); border-radius:5px; padding:3px 8px; font-variant-numeric:tabular-nums}

.subs{display:flex; flex-wrap:wrap; gap:5px; margin:-3px 0 12px}
.sub{font-size:10.5px; border-radius:4px; padding:2px 7px; color:var(--ink-2); background:#eef4f9}
.sub.band-high{background:var(--high-bg)} .sub.band-mid{background:var(--mid-bg)} .sub.band-low{background:var(--low-bg)}
.sub b{font-variant-numeric:tabular-nums}

.q-flag{font-size:12.5px; color:var(--low); background:var(--low-bg); border-radius:7px; padding:9px 12px}
.q-deductions{display:flex; flex-direction:column; gap:5px; margin-top:11px}
.ded{font-size:11.5px; color:var(--low); background:var(--low-bg); border-radius:5px; padding:5px 9px}
.q-note{font-size:11.5px; color:var(--mid); background:var(--mid-bg); border-radius:5px; padding:5px 9px; margin-top:7px}

.transcript{margin-top:12px; border-top:1px solid var(--line); padding-top:10px}
.transcript summary{font-size:12px; color:var(--accent); cursor:pointer; font-weight:600; user-select:none}
.transcript p{font-size:12.5px; color:var(--ink-2); line-height:1.65; margin:9px 0 0; white-space:pre-wrap}

/* table */
.table{width:100%; border-collapse:collapse; font-size:12.5px}
.table th{text-align:left; font-size:11px; text-transform:uppercase; letter-spacing:.05em; color:var(--muted); padding:0 10px 8px; border-bottom:1px solid var(--line)}
.table td{padding:10px; border-bottom:1px solid #edf3f8; vertical-align:top}
.table tr:last-child td{border-bottom:none}
.neg{color:var(--low); font-weight:700; font-variant-numeric:tabular-nums}
.table-note{font-size:11.5px; color:var(--muted); margin:12px 0 0; line-height:1.5}

.reco-card{background:linear-gradient(180deg,var(--brand-tint),#f6fbfe); border-color:var(--brand-tint-2)}
.reco{font-size:13px; line-height:1.75; color:var(--ink-2); white-space:pre-line}

.footer{font-size:11px; color:var(--muted); text-align:center; margin-top:28px; line-height:1.6}

@media (max-width:820px){
  .stat-strip{grid-template-columns:repeat(2,1fr)}
  .grid-2{grid-template-columns:1fr}
  .header{flex-direction:column; align-items:flex-start}
}
@media print{
  /* The score bars and band chips ARE the information here — a bar printed
     white says "zero". Force backgrounds through rather than relying on the
     PDF renderer being called with printBackground. */
  *{-webkit-print-color-adjust:exact; print-color-adjust:exact}
  body{background:#fff}
  .page{max-width:none; padding:0}
  .card,.header,.stat{break-inside:avoid; box-shadow:none}
  .q-card{break-inside:avoid}
  .transcript[open] summary{display:none}
  .pipeline{overflow:visible}
}
`;

module.exports = { renderDashboardHtml };
